# Generated by Django 3.0.1 on 2023-10-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_prints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='prints',
        ),
    ]
