# Generated by Django 3.0.1 on 2023-10-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0003_remove_orderlineitem_prints'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='prints',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.PrintOptions'),
            preserve_default=False,
        ),
    ]
