# Generated by Django 3.0.1 on 2023-10-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_prints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='prints',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
